<?php

namespace TransportBundle\Repository;

/**
 * ChauffeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChauffeurRepository extends \Doctrine\ORM\EntityRepository
{
}
