<?php

namespace TransportBundle\Repository;

/**
 * LigneTransportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneTransportRepository extends \Doctrine\ORM\EntityRepository
{
}
