<?php

namespace ClubBundle\Repository;

/**
 * ActiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActiviteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findClub($id)
    {
        return $this->getEntityManager()
            ->createQuery(
                "SELECT a
       FROM ClubBundle:Activite a
        WHERE a.club=:id"
            )
            ->setParameter('id',$id)
            ->getResult();
    }
}
